permalink: /:year/:month/:day/:title.html
paginate: 10
author: 
  name: maomu
  email: yansu0711@gmail.com
  link: http://yansu.org
  enlink: http://en.yansu.org
title: maomu
locals:
  tags: 标签
  about: 关于
active: 技术
subscribe_rss: /pages/atom.xml
markdown: redcarpet

