markdown: rdiscount
pygments: true
permalink: /:categories/:title.html
plugins: ./_plugins
paginate: 5

safe: false

#站点基础配置
title: 白板报
subTitle: The White Board
description: 作家，编剧，代表作《正版语文》、《疯狂短信》
url: http://baibanbao.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 网志
    url: /notes.html
    icon: icon-reorder
    class: none
  - text: 小说
    url: /novels.html
    icon: icon-heart
    class: none
  - text: 联系
    url: /contact.html
    icon: icon-envelope-alt
    class: none

page:
  - text: 所有文章
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: 王佩
