permalink: /:year/:month/:day/:title.html
paginate: 10
author: 
  name: zhangmengyuan
  email: yansu0711@gmail.com
  link: http://zhangmengyuan.github.io
  enlink: http://zhangmengyuan.github.io
title: maomu
locals:
  tags: 标签
  about: 关于
active: 技术
subscribe_rss: /pages/atom.xml
markdown: redcarpet

