markdown: rdiscount
pygments: true
permalink: /:categories/:title.html
plugins: ./_plugins
paginate: 5

safe: false

#站点基础配置
title: 苏民
subTitle: 不会画画的PM不是好的小说家
description: 不会画画的PM不是好的小说家
url: http://sumin.org
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 网志
    url: /notes.html
    icon: icon-reorder
    class: none
  - text: 小说
    url: /novels.html
    icon: icon-envelope-alt
    class: none
  - text: 联系
    url: /contact.html
    icon: icon-heart
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: 苏民
